import '../../../core/abstract/presentation/abstract.app_color.dart';

class PrimitiveColors {
  static const CustomAppColor white = CustomAppColor(0xFFFFFFFF); // White
  static const CustomAppColor black = CustomAppColor(0xFF000000); // Black
  static const CustomAppColor transparent = CustomAppColor(0x00000000);
  static const CustomAppColor red = CustomAppColor(0xFFEB5757); // Red
  static const CustomAppColor green = CustomAppColor(0xFF27AE60); // Green
  static const CustomAppColor blue = CustomAppColor(0xFF2F97C1); // Blue
  static const CustomAppColor orange = CustomAppColor(0xFFF49342); // Orange
  static const CustomAppColor pink = CustomAppColor(0xFFEC407A); // Pink

  static const CustomAppColor hintText = CustomAppColor(0xFF828282); // Stroke
  static const CustomAppColor stroke = CustomAppColor(0xFFE0E0E0); // Stroke
  static const CustomAppColor inactive = CustomAppColor(0xFF828282); // Stroke

  static const CustomAppColor primary = CustomAppColor(0xFFFFC800); // Primary
  static const CustomAppColor onPrimary = CustomAppColor(
    0xFF000000,
  ); // On Primary
  static const CustomAppColor primaryDisabled = CustomAppColor(
    0xFFE0E0E0,
  ); // Primary Disabled
  static const CustomAppColor onPrimaryDisabled = CustomAppColor(
    0xFF828282,
  ); // On Primary Disabled

  static const CustomAppColor secondary = CustomAppColor(
    0xFF04C243,
  ); // Secondary
  static const CustomAppColor onSecondary = CustomAppColor(
    0xFFFFFFFF,
  ); // On Secondary
  static const CustomAppColor secondaryDisabled = CustomAppColor(
    0xFFE0E0E0,
  ); // Secondary Disabled
  static const CustomAppColor onSecondaryDisabled = CustomAppColor(
    0xFF828282,
  ); // On Secondary Disabled

  //----

  static const CustomAppColor grey0 = CustomAppColor(0xff000000);
  static const CustomAppColor grey20 = CustomAppColor(0xff040406);
  static const CustomAppColor grey40 = CustomAppColor(0xff08090c);
  static const CustomAppColor grey60 = CustomAppColor(0xff0c0e12);
  static const CustomAppColor grey80 = CustomAppColor(0xff101318);
  static const CustomAppColor grey100 = CustomAppColor(0xff14181e);
  static const CustomAppColor grey110 = CustomAppColor(0xff161b21);
  static const CustomAppColor grey120 = CustomAppColor(0xff181d24);
  static const CustomAppColor grey130 = CustomAppColor(0xff1a2027);
  static const CustomAppColor grey140 = CustomAppColor(0xff1c222a);
  static const CustomAppColor grey150 = CustomAppColor(0xff1e242d);
  static const CustomAppColor grey160 = CustomAppColor(0xff202731);
  static const CustomAppColor grey170 = CustomAppColor(0xff222934);
  static const CustomAppColor grey180 = CustomAppColor(0xff242c37);
  static const CustomAppColor grey190 = CustomAppColor(0xff262e3a);
  static const CustomAppColor grey200 = CustomAppColor(0xff28313d);
  static const CustomAppColor grey220 = CustomAppColor(0xff2c3643);
  static const CustomAppColor grey240 = CustomAppColor(0xff303b49);
  static const CustomAppColor grey260 = CustomAppColor(0xff34404f);
  static const CustomAppColor grey280 = CustomAppColor(0xff384455);
  static const CustomAppColor grey300 = CustomAppColor(0xff3d495b);
  static const CustomAppColor grey350 = CustomAppColor(0xff47566b);
  static const CustomAppColor grey400 = CustomAppColor(0xff51627a);
  static const CustomAppColor grey450 = CustomAppColor(0xff5b6e89);
  static const CustomAppColor grey500 = CustomAppColor(0xff657b99);
  static const CustomAppColor grey550 = CustomAppColor(0xff7588a3);
  static const CustomAppColor grey600 = CustomAppColor(0xff8495ad);
  static const CustomAppColor grey650 = CustomAppColor(0xff93a2b7);
  static const CustomAppColor grey700 = CustomAppColor(0xffa3afc1);
  static const CustomAppColor grey750 = CustomAppColor(0xffb2bdcc);
  static const CustomAppColor grey800 = CustomAppColor(0xffc1cad6);
  static const CustomAppColor grey810 = CustomAppColor(0xffc4ccd8);
  static const CustomAppColor grey820 = CustomAppColor(0xffc7cfda);
  static const CustomAppColor grey830 = CustomAppColor(0xffcad2dc);
  static const CustomAppColor grey840 = CustomAppColor(0xffcdd4de);
  static const CustomAppColor grey850 = CustomAppColor(0xffd1d7e0);
  static const CustomAppColor grey860 = CustomAppColor(0xffd4dae2);
  static const CustomAppColor grey870 = CustomAppColor(0xffd7dce4);
  static const CustomAppColor grey880 = CustomAppColor(0xffdadfe6);
  static const CustomAppColor grey890 = CustomAppColor(0xffdde2e8);
  static const CustomAppColor grey900 = CustomAppColor(0xffe0e4ea);
  static const CustomAppColor grey910 = CustomAppColor(0xffe3e7ec);
  static const CustomAppColor grey920 = CustomAppColor(0xffe6e9ee);
  static const CustomAppColor grey930 = CustomAppColor(0xffe9ecf0);
  static const CustomAppColor grey940 = CustomAppColor(0xffeceff2);
  static const CustomAppColor grey950 = CustomAppColor(0xffeff1f4);
  static const CustomAppColor grey960 = CustomAppColor(0xfff2f4f6);
  static const CustomAppColor grey970 = CustomAppColor(0xfff5f7f8);
  static const CustomAppColor grey980 = CustomAppColor(0xfff8f9fa);
  static const CustomAppColor grey990 = CustomAppColor(0xfffbfcfc);
  static const CustomAppColor grey1000 = CustomAppColor(0xffffffff);
  static const CustomAppColor error0 = CustomAppColor(0xff000000);
  static const CustomAppColor error20 = CustomAppColor(0xff0a0500);
  static const CustomAppColor error40 = CustomAppColor(0xff140a00);
  static const CustomAppColor error60 = CustomAppColor(0xff1e0f00);
  static const CustomAppColor error80 = CustomAppColor(0xff281400);
  static const CustomAppColor error100 = CustomAppColor(0xff321900);
  static const CustomAppColor error110 = CustomAppColor(0xff371b00);
  static const CustomAppColor error120 = CustomAppColor(0xff3c1e00);
  static const CustomAppColor error130 = CustomAppColor(0xff412001);
  static const CustomAppColor error140 = CustomAppColor(0xff462301);
  static const CustomAppColor error150 = CustomAppColor(0xff4b2501);
  static const CustomAppColor error160 = CustomAppColor(0xff502801);
  static const CustomAppColor error170 = CustomAppColor(0xff552a01);
  static const CustomAppColor error180 = CustomAppColor(0xff5a2d01);
  static const CustomAppColor error190 = CustomAppColor(0xff5f2f01);
  static const CustomAppColor error200 = CustomAppColor(0xff643201);
  static const CustomAppColor error220 = CustomAppColor(0xff6e3701);
  static const CustomAppColor error240 = CustomAppColor(0xff783c01);
  static const CustomAppColor error260 = CustomAppColor(0xff824102);
  static const CustomAppColor error280 = CustomAppColor(0xff8c4602);
  static const CustomAppColor error300 = CustomAppColor(0xff964b02);
  static const CustomAppColor error350 = CustomAppColor(0xffaf5702);
  static const CustomAppColor error400 = CustomAppColor(0xffc86403);
  static const CustomAppColor error450 = CustomAppColor(0xffe17003);
  static const CustomAppColor error500 = CustomAppColor(0xfffa7d04);
  static const CustomAppColor error550 = CustomAppColor(0xfffb8a1d);
  static const CustomAppColor error600 = CustomAppColor(0xfffb9736);
  static const CustomAppColor error650 = CustomAppColor(0xfffca44f);
  static const CustomAppColor error700 = CustomAppColor(0xfffcb168);
  static const CustomAppColor error750 = CustomAppColor(0xfffcbe81);
  static const CustomAppColor error800 = CustomAppColor(0xfffdcb9a);
  static const CustomAppColor error810 = CustomAppColor(0xfffdcd9f);
  static const CustomAppColor error820 = CustomAppColor(0xfffdd0a4);
  static const CustomAppColor error830 = CustomAppColor(0xfffdd2a9);
  static const CustomAppColor error840 = CustomAppColor(0xfffdd5ae);
  static const CustomAppColor error850 = CustomAppColor(0xfffdd8b3);
  static const CustomAppColor error860 = CustomAppColor(0xfffddab8);
  static const CustomAppColor error870 = CustomAppColor(0xfffdddbd);
  static const CustomAppColor error880 = CustomAppColor(0xfffedfc2);
  static const CustomAppColor error890 = CustomAppColor(0xfffee2c7);
  static const CustomAppColor error900 = CustomAppColor(0xfffee5cc);
  static const CustomAppColor error910 = CustomAppColor(0xfffee7d1);
  static const CustomAppColor error920 = CustomAppColor(0xfffeead6);
  static const CustomAppColor error930 = CustomAppColor(0xfffeecdb);
  static const CustomAppColor error940 = CustomAppColor(0xfffeefe0);
  static const CustomAppColor error950 = CustomAppColor(0xfffef2e5);
  static const CustomAppColor error960 = CustomAppColor(0xfffef4ea);
  static const CustomAppColor error970 = CustomAppColor(0xfffef7ef);
  static const CustomAppColor error980 = CustomAppColor(0xfffef9f4);
  static const CustomAppColor error990 = CustomAppColor(0xfffefcf9);
  static const CustomAppColor error1000 = CustomAppColor(0xffffffff);
  static const CustomAppColor primary0 = CustomAppColor(0xff000000);
  static const CustomAppColor primary20 = CustomAppColor(0xff0a0800);
  static const CustomAppColor primary40 = CustomAppColor(0xff141000);
  static const CustomAppColor primary60 = CustomAppColor(0xff1e1800);
  static const CustomAppColor primary80 = CustomAppColor(0xff282000);
  static const CustomAppColor primary100 = CustomAppColor(0xff332800);
  static const CustomAppColor primary110 = CustomAppColor(0xff382c00);
  static const CustomAppColor primary120 = CustomAppColor(0xff3d3000);
  static const CustomAppColor primary130 = CustomAppColor(0xff423400);
  static const CustomAppColor primary140 = CustomAppColor(0xff473800);
  static const CustomAppColor primary150 = CustomAppColor(0xff4c3c00);
  static const CustomAppColor primary160 = CustomAppColor(0xff514000);
  static const CustomAppColor primary170 = CustomAppColor(0xff564400);
  static const CustomAppColor primary180 = CustomAppColor(0xff5b4800);
  static const CustomAppColor primary190 = CustomAppColor(0xff604c00);
  static const CustomAppColor primary200 = CustomAppColor(0xff665000);
  static const CustomAppColor primary220 = CustomAppColor(0xff705800);
  static const CustomAppColor primary240 = CustomAppColor(0xff7a6000);
  static const CustomAppColor primary260 = CustomAppColor(0xff846800);
  static const CustomAppColor primary280 = CustomAppColor(0xff8e7000);
  static const CustomAppColor primary300 = CustomAppColor(0xff997800);
  static const CustomAppColor primary350 = CustomAppColor(0xffb28b00);
  static const CustomAppColor primary400 = CustomAppColor(0xffcca000);
  static const CustomAppColor primary450 = CustomAppColor(0xffe5b400);
  static const CustomAppColor primary500 = CustomAppColor(0xffffc800);
  static const CustomAppColor primary550 = CustomAppColor(0xffffcd19);
  static const CustomAppColor primary600 = CustomAppColor(0xffffd332);
  static const CustomAppColor primary650 = CustomAppColor(0xfffed84c);
  static const CustomAppColor primary700 = CustomAppColor(0xffffde65);
  static const CustomAppColor primary750 = CustomAppColor(0xffffe37f);
  static const CustomAppColor primary800 = CustomAppColor(0xffffe999);
  static const CustomAppColor primary810 = CustomAppColor(0xffffea9e);
  static const CustomAppColor primary820 = CustomAppColor(0xfffeeba3);
  static const CustomAppColor primary830 = CustomAppColor(0xffffeca8);
  static const CustomAppColor primary840 = CustomAppColor(0xfffeedad);
  static const CustomAppColor primary850 = CustomAppColor(0xffffeeb2);
  static const CustomAppColor primary860 = CustomAppColor(0xfffeefb7);
  static const CustomAppColor primary870 = CustomAppColor(0xfffff0bc);
  static const CustomAppColor primary880 = CustomAppColor(0xfffef1c1);
  static const CustomAppColor primary890 = CustomAppColor(0xfffff2c6);
  static const CustomAppColor primary900 = CustomAppColor(0xfffef3cc);
  static const CustomAppColor primary910 = CustomAppColor(0xfffff5d1);
  static const CustomAppColor primary920 = CustomAppColor(0xfffef6d6);
  static const CustomAppColor primary930 = CustomAppColor(0xfffff7db);
  static const CustomAppColor primary940 = CustomAppColor(0xfffff8e0);
  static const CustomAppColor primary950 = CustomAppColor(0xfffff9e5);
  static const CustomAppColor primary960 = CustomAppColor(0xfffffaea);
  static const CustomAppColor primary970 = CustomAppColor(0xfffffbef);
  static const CustomAppColor primary980 = CustomAppColor(0xfffffcf4);
  static const CustomAppColor primary990 = CustomAppColor(0xfffffdf9);
  static const CustomAppColor primary1000 = CustomAppColor(0xffffffff);
  static const CustomAppColor secondary0 = CustomAppColor(0xff000000);
  static const CustomAppColor secondary20 = CustomAppColor(0xff00050a);
  static const CustomAppColor secondary40 = CustomAppColor(0xff000b14);
  static const CustomAppColor secondary60 = CustomAppColor(0xff00101e);
  static const CustomAppColor secondary80 = CustomAppColor(0xff001628);
  static const CustomAppColor secondary100 = CustomAppColor(0xff001c33);
  static const CustomAppColor secondary110 = CustomAppColor(0xff001f38);
  static const CustomAppColor secondary120 = CustomAppColor(0xff00213d);
  static const CustomAppColor secondary130 = CustomAppColor(0xff002442);
  static const CustomAppColor secondary140 = CustomAppColor(0xff002747);
  static const CustomAppColor secondary150 = CustomAppColor(0xff002a4c);
  static const CustomAppColor secondary160 = CustomAppColor(0xff002d51);
  static const CustomAppColor secondary170 = CustomAppColor(0xff002f56);
  static const CustomAppColor secondary180 = CustomAppColor(0xff00325b);
  static const CustomAppColor secondary190 = CustomAppColor(0xff003560);
  static const CustomAppColor secondary200 = CustomAppColor(0xff003866);
  static const CustomAppColor secondary220 = CustomAppColor(0xff003e70);
  static const CustomAppColor secondary240 = CustomAppColor(0xff00437a);
  static const CustomAppColor secondary260 = CustomAppColor(0xff004984);
  static const CustomAppColor secondary280 = CustomAppColor(0xff004f8e);
  static const CustomAppColor secondary300 = CustomAppColor(0xff005499);
  static const CustomAppColor secondary350 = CustomAppColor(0xff0062b2);
  static const CustomAppColor secondary400 = CustomAppColor(0xff0070cc);
  static const CustomAppColor secondary450 = CustomAppColor(0xff007fe5);
  static const CustomAppColor secondary500 = CustomAppColor(0xff008dff);
  static const CustomAppColor secondary550 = CustomAppColor(0xff1998ff);
  static const CustomAppColor secondary600 = CustomAppColor(0xff32a3ff);
  static const CustomAppColor secondary650 = CustomAppColor(0xff4caffe);
  static const CustomAppColor secondary700 = CustomAppColor(0xff65baff);
  static const CustomAppColor secondary750 = CustomAppColor(0xff7fc6ff);
  static const CustomAppColor secondary800 = CustomAppColor(0xff99d1ff);
  static const CustomAppColor secondary810 = CustomAppColor(0xff9ed3ff);
  static const CustomAppColor secondary820 = CustomAppColor(0xffa3d6fe);
  static const CustomAppColor secondary830 = CustomAppColor(0xffa8d8ff);
  static const CustomAppColor secondary840 = CustomAppColor(0xffaddafe);
  static const CustomAppColor secondary850 = CustomAppColor(0xffb2dcff);
  static const CustomAppColor secondary860 = CustomAppColor(0xffb7dffe);
  static const CustomAppColor secondary870 = CustomAppColor(0xffbce1ff);
  static const CustomAppColor secondary880 = CustomAppColor(0xffc1e3fe);
  static const CustomAppColor secondary890 = CustomAppColor(0xffc6e5ff);
  static const CustomAppColor secondary900 = CustomAppColor(0xffcce8fe);
  static const CustomAppColor secondary910 = CustomAppColor(0xffd1eaff);
  static const CustomAppColor secondary920 = CustomAppColor(0xffd6ecfe);
  static const CustomAppColor secondary930 = CustomAppColor(0xffdbefff);
  static const CustomAppColor secondary940 = CustomAppColor(0xffe0f1ff);
  static const CustomAppColor secondary950 = CustomAppColor(0xffe5f3ff);
  static const CustomAppColor secondary960 = CustomAppColor(0xffeaf5ff);
  static const CustomAppColor secondary970 = CustomAppColor(0xffeff8ff);
  static const CustomAppColor secondary980 = CustomAppColor(0xfff4faff);
  static const CustomAppColor secondary990 = CustomAppColor(0xfff9fcff);
  static const CustomAppColor secondary1000 = CustomAppColor(0xffffffff);
  static const CustomAppColor tertiary0 = CustomAppColor(0xff000000);
  static const CustomAppColor tertiary20 = CustomAppColor(0xff0a0700);
  static const CustomAppColor tertiary40 = CustomAppColor(0xff140e00);
  static const CustomAppColor tertiary60 = CustomAppColor(0xff1e1500);
  static const CustomAppColor tertiary80 = CustomAppColor(0xff281c00);
  static const CustomAppColor tertiary100 = CustomAppColor(0xff332300);
  static const CustomAppColor tertiary110 = CustomAppColor(0xff382600);
  static const CustomAppColor tertiary120 = CustomAppColor(0xff3d2a00);
  static const CustomAppColor tertiary130 = CustomAppColor(0xff422d00);
  static const CustomAppColor tertiary140 = CustomAppColor(0xff473100);
  static const CustomAppColor tertiary150 = CustomAppColor(0xff4c3400);
  static const CustomAppColor tertiary160 = CustomAppColor(0xff513800);
  static const CustomAppColor tertiary170 = CustomAppColor(0xff563b00);
  static const CustomAppColor tertiary180 = CustomAppColor(0xff5b3f00);
  static const CustomAppColor tertiary190 = CustomAppColor(0xff604200);
  static const CustomAppColor tertiary200 = CustomAppColor(0xff664600);
  static const CustomAppColor tertiary220 = CustomAppColor(0xff704d00);
  static const CustomAppColor tertiary240 = CustomAppColor(0xff7a5400);
  static const CustomAppColor tertiary260 = CustomAppColor(0xff845b00);
  static const CustomAppColor tertiary280 = CustomAppColor(0xff8e6200);
  static const CustomAppColor tertiary300 = CustomAppColor(0xff996900);
  static const CustomAppColor tertiary350 = CustomAppColor(0xffb27a00);
  static const CustomAppColor tertiary400 = CustomAppColor(0xffcc8c00);
  static const CustomAppColor tertiary450 = CustomAppColor(0xffe59e00);
  static const CustomAppColor tertiary500 = CustomAppColor(0xffffaf00);
  static const CustomAppColor tertiary550 = CustomAppColor(0xffffb719);
  static const CustomAppColor tertiary600 = CustomAppColor(0xffffbf32);
  static const CustomAppColor tertiary650 = CustomAppColor(0xfffec74c);
  static const CustomAppColor tertiary700 = CustomAppColor(0xffffcf65);
  static const CustomAppColor tertiary750 = CustomAppColor(0xffffd77f);
  static const CustomAppColor tertiary800 = CustomAppColor(0xffffdf99);
  static const CustomAppColor tertiary810 = CustomAppColor(0xffffe09e);
  static const CustomAppColor tertiary820 = CustomAppColor(0xfffee2a3);
  static const CustomAppColor tertiary830 = CustomAppColor(0xffffe3a8);
  static const CustomAppColor tertiary840 = CustomAppColor(0xfffee5ad);
  static const CustomAppColor tertiary850 = CustomAppColor(0xffffe7b2);
  static const CustomAppColor tertiary860 = CustomAppColor(0xfffee8b7);
  static const CustomAppColor tertiary870 = CustomAppColor(0xffffeabc);
  static const CustomAppColor tertiary880 = CustomAppColor(0xfffeebc1);
  static const CustomAppColor tertiary890 = CustomAppColor(0xffffedc6);
  static const CustomAppColor tertiary900 = CustomAppColor(0xfffeefcc);
  static const CustomAppColor tertiary910 = CustomAppColor(0xfffff0d1);
  static const CustomAppColor tertiary920 = CustomAppColor(0xfffef2d6);
  static const CustomAppColor tertiary930 = CustomAppColor(0xfffff3db);
  static const CustomAppColor tertiary940 = CustomAppColor(0xfffff5e0);
  static const CustomAppColor tertiary950 = CustomAppColor(0xfffff7e5);
  static const CustomAppColor tertiary960 = CustomAppColor(0xfffff8ea);
  static const CustomAppColor tertiary970 = CustomAppColor(0xfffffaef);
  static const CustomAppColor tertiary980 = CustomAppColor(0xfffffbf4);
  static const CustomAppColor tertiary990 = CustomAppColor(0xfffffdf9);
  static const CustomAppColor tertiary1000 = CustomAppColor(0xffffffff);
  static const CustomAppColor greyVariant0 = CustomAppColor(0xff000000);
  static const CustomAppColor greyVariant20 = CustomAppColor(0xff050504);
  static const CustomAppColor greyVariant40 = CustomAppColor(0xff0a0a09);
  static const CustomAppColor greyVariant60 = CustomAppColor(0xff100f0e);
  static const CustomAppColor greyVariant80 = CustomAppColor(0xff151413);
  static const CustomAppColor greyVariant100 = CustomAppColor(0xff1a1918);
  static const CustomAppColor greyVariant110 = CustomAppColor(0xff1d1b1a);
  static const CustomAppColor greyVariant120 = CustomAppColor(0xff201e1c);
  static const CustomAppColor greyVariant130 = CustomAppColor(0xff22201f);
  static const CustomAppColor greyVariant140 = CustomAppColor(0xff252321);
  static const CustomAppColor greyVariant150 = CustomAppColor(0xff282524);
  static const CustomAppColor greyVariant160 = CustomAppColor(0xff2b2826);
  static const CustomAppColor greyVariant170 = CustomAppColor(0xff2d2a28);
  static const CustomAppColor greyVariant180 = CustomAppColor(0xff302d2b);
  static const CustomAppColor greyVariant190 = CustomAppColor(0xff332f2d);
  static const CustomAppColor greyVariant200 = CustomAppColor(0xff353230);
  static const CustomAppColor greyVariant220 = CustomAppColor(0xff3b3735);
  static const CustomAppColor greyVariant240 = CustomAppColor(0xff403c39);
  static const CustomAppColor greyVariant260 = CustomAppColor(0xff45413e);
  static const CustomAppColor greyVariant280 = CustomAppColor(0xff4b4643);
  static const CustomAppColor greyVariant300 = CustomAppColor(0xff504b48);
  static const CustomAppColor greyVariant350 = CustomAppColor(0xff5e5854);
  static const CustomAppColor greyVariant400 = CustomAppColor(0xff6b6460);
  static const CustomAppColor greyVariant450 = CustomAppColor(0xff78716c);
  static const CustomAppColor greyVariant500 = CustomAppColor(0xff867e78);
  static const CustomAppColor greyVariant550 = CustomAppColor(0xff928b86);
  static const CustomAppColor greyVariant600 = CustomAppColor(0xff9e9793);
  static const CustomAppColor greyVariant650 = CustomAppColor(0xffaaa4a0);
  static const CustomAppColor greyVariant700 = CustomAppColor(0xffb6b1ae);
  static const CustomAppColor greyVariant750 = CustomAppColor(0xffc2bebb);
  static const CustomAppColor greyVariant800 = CustomAppColor(0xffcecbc9);
  static const CustomAppColor greyVariant810 = CustomAppColor(0xffd1cecb);
  static const CustomAppColor greyVariant820 = CustomAppColor(0xffd3d0ce);
  static const CustomAppColor greyVariant830 = CustomAppColor(0xffd6d3d1);
  static const CustomAppColor greyVariant840 = CustomAppColor(0xffd8d5d3);
  static const CustomAppColor greyVariant850 = CustomAppColor(0xffdad8d6);
  static const CustomAppColor greyVariant860 = CustomAppColor(0xffdddad9);
  static const CustomAppColor greyVariant870 = CustomAppColor(0xffdfdddc);
  static const CustomAppColor greyVariant880 = CustomAppColor(0xffe2e0de);
  static const CustomAppColor greyVariant890 = CustomAppColor(0xffe4e2e1);
  static const CustomAppColor greyVariant900 = CustomAppColor(0xffe6e5e4);
  static const CustomAppColor greyVariant910 = CustomAppColor(0xffe9e7e6);
  static const CustomAppColor greyVariant920 = CustomAppColor(0xffebeae9);
  static const CustomAppColor greyVariant930 = CustomAppColor(0xffeeecec);
  static const CustomAppColor greyVariant940 = CustomAppColor(0xfff0efee);
  static const CustomAppColor greyVariant950 = CustomAppColor(0xfff2f2f1);
  static const CustomAppColor greyVariant960 = CustomAppColor(0xfff5f4f4);
  static const CustomAppColor greyVariant970 = CustomAppColor(0xfff7f7f6);
  static const CustomAppColor greyVariant980 = CustomAppColor(0xfffaf9f9);
  static const CustomAppColor greyVariant990 = CustomAppColor(0xfffcfcfc);
  static const CustomAppColor greyVariant1000 = CustomAppColor(0xffffffff);
}
